### PR TITLE
Docker improvements

### PR DESCRIPTION
**Pull request by Graham42**
- Don't bundle secrets in container
- Improved docker build caching.
- Made the Dockerfile more versatile so it can be used for a server or for testing.

Usage:

```sh
docker run -i -t --rm \
    -v "$(pwd)/.env:/app/.env" \
    delete-merged-branch \
        <probot-command> /app/index.js <params>
```

### CODE REVIEW

**Comment by Graham42** [comment]
The build is failing with 
> sonar-scanner
> sonar-scanner: command not found
> The command "sonar-scanner" exited with 127.

This seems unrelated to my changes?

**Comment by SvanBoxel** [comment]
Hey @Graham42 ! Thanks for your contributions. I'm looking into the sonar-scanner error

**Comment by SvanBoxel** [comment]
@Graham42 I'm merging your pull request, this is a known issue with forks.  https://docs.travis-ci.com/user/sonarcloud/#upcoming-improvements
Thanks again!

**Pull request merged**
