### PR TITLE
feat(app): add a config to delete closed pr branch

### LINKED ISSUE #106: config to delete closed PR
https://github.com/SvanBoxel/delete-merged-branch/blob/ecb075b8a034687a78aeb55515d553ece81c0d8e/lib/delete-merged-branch.js#L21-L24

I think yml file should allow a config which will also delete a branch if it's closed.

### PR DESCRIPTION
**Pull request by cyberhck**
delete_closed_pr key on your yaml file will now also delete closed branches

closes #106

### CODE REVIEW

**Comment by cyberhck** [comment]
it has some npm error, what do I do about this? @SvanBoxel

**Comment by cyberhck** [comment]
@SvanBoxel I can try deleting .npmrc on not master branches and fix that if you'd like

**Comment by cyberhck** [comment]
@SvanBoxel can we instead have this default to deleting closed PRs as well?

**Comment by cyberhck** [comment]
hey @SvanBoxel do you mind taking a look? Thanks.

**Comment by SvanBoxel** [comment]
Hey, sorry I completely missed this PR! Looks good from my side (ignoring the CI issue). Could you update the readme as well? Thanks!

**Comment by cyberhck** [comment]
I'll see if I can update env so I can set default to delete the merged branch as well :)

**Comment by cyberhck** [comment]
@SvanBoxel please check the latest version, if there's any styling issue, I'll fix it, other than that, it should be working perfectly same for you, but when I deploy my own instance for my private enterprise, I should be able to set a environment variable and delete also closed branches :)

Thanks.

**Comment by cyberhck** [comment]
@SvanBoxel hey, this is ready, in case you missed the last notification.

**Comment by cyberhck** [comment]
@SvanBoxel hey, this is ready, in case you missed the last notification.

**Comment by SvanBoxel** [comment]
Good work @cyberhck 🚀

**Pull request merged**
